### Variables
@baseUrl = http://localhost:3000
@contentType = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NDM4YWUwMC04YzI5LTQyMzktYTE1NC1kMmI2MDBlZDA2ODAiLCJlbWFpbCI6ImphbmUyQGV4YW1wbGUuY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3Njc5NzY2NzIsImV4cCI6MTc2ODA2MzA3Mn0.dLTCt-B-HFem7pZi82IQfpP111jWRYSlXjUFfULspKc
@ADMIN_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzZjc4OWVkOC01YTQwLTQ0ZmQtYmNiZC1mMDhlYmM0YjQ0MDEiLCJlbWFpbCI6ImphbmUzQGV4YW1wbGUuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzY3OTc2NjU3LCJleHAiOjE3NjgwNjMwNTd9.EuVjlUqVOJ60PfdbIuKcArV_2fBak9IbF8V99QcYF4Y

### Health Check
GET {{baseUrl}}/health

### Auth - Register
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "email": "user@example.com",
  "password1": "password123",
  "password2": "password123",
  "fullName": "John Doe"
}

### Auth - Login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "jane2@example.com",
  "password": "securepassword"
}

### Auth - Change Password
POST {{baseUrl}}/auth/change-password
Content-Type: {{contentType}}

{
  "currentPassword": "securepassword",
  "newPassword1": "newsecurepassword",
  "newPassword2": "newsecurepassword"
}

### Auth - Get Profile
GET {{baseUrl}}/auth/profile
# Authorization: Bearer {{ADMIN_TOKEN}}
Authorization: Bearer {{token}}

### Users
@userId = 110e6e64-f4d1-40f9-a4bc-71711fac7691
### Users - Get All
GET {{baseUrl}}/users
Authorization: Bearer {{token}}

### Users - Get By ID
GET {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{token}}

### Users - Update
PATCH  {{baseUrl}}/users/{{userId}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "fullName": "Jane Smith 55",
  "email": "jane@example.com"
}

### Users - Delete
DELETE {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{token}}

### Categories
@categoryId = f4e6ce22-70e4-42f0-a940-2195ad29240d

### Categories - Create
POST {{baseUrl}}/categories
Content-Type: {{contentType}}

{
  "name": "Fast Food",
  "description": "Quick and convenient meals"
}

### Categories - Get All
GET {{baseUrl}}/categories

### Categories - Get By ID
GET {{baseUrl}}/categories/{{categoryId}}

### Categories - Update
PATCH {{baseUrl}}/categories/{{categoryId}}
Content-Type: {{contentType}}

{
  "name": "Updated Fast Food",
  "description": "Updated description for quick meals"
}

### Categories - Delete
DELETE {{baseUrl}}/categories/{{categoryId}}