### Variables
@baseUrl = http://localhost:5555/api/v1
@contentType = application/json
@ADMIN_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1MmVlZmYxMS00ZWIwLTQ1MmItYTBiNy1lMDU5N2MxZDlhM2QiLCJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjgyMTA0NTYsImV4cCI6MTc2ODIxNDA1Nn0.8icuufau_UxZ0UPX7QltZqd4S_uPaWS4ihG_dAu__Vw
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3OTkxMWMwMi1kYTlkLTQyNGMtODMzMC1mYmU3ZmZkOTFkNDUiLCJlbWFpbCI6InVzZXIxQGV4YW1wbGUuY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3NjgyMTA0NjgsImV4cCI6MTc2ODIxNDA2OH0.sfVwaJd6eocErPqlP0KuBRDzlWHul4M15Sf1AHLY0vo

### Health Check
GET {{baseUrl}}/health

### Auth

### Auth - Register
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "email": "user2@example.com",
  "password1": "SecureP@ssw0rd!123",
  "password2": "SecureP@ssw0rd!123",
  "fullName": "John Doe 3",
  "address": "123 Uttara, Dhaka, Bangladesh"
}

### Auth - Login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "user1@example.com",
  "password": "SecureP@ssw0rd!123"
}

### Auth - Change Password
POST {{baseUrl}}/auth/change-password
Content-Type: {{contentType}}

{
  "currentPassword": "SecureP@ssw0rd!123",
  "newPassword1": "NewSecure@ssw0rd!123",
  "newPassword2": "NewSecure@ssw0rd!123"
}

### Auth - Get Profile
GET {{baseUrl}}/auth/verify
# Authorization: Bearer {{ADMIN_TOKEN}}
Authorization: Bearer {{token}}

### Users
@userId = 110e6e64-f4d1-40f9-a4bc-71711fac7691
### Users - Get All
GET {{baseUrl}}/users
Authorization: Bearer {{ADMIN_TOKEN}}

### Users - Get By ID
GET {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{ADMIN_TOKEN}}
### Users - Update
PATCH  {{baseUrl}}/users/{{userId}}
Content-Type: {{contentType}}
Authorization: Bearer {{ADMIN_TOKEN}}

{
  "fullName": "Jane Smith 55",
  "email": "jane@example.com"
}

### Users - Delete
DELETE {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{ADMIN_TOKEN}}

### Categories
@categoryId = b80b1c4a-0756-4fb4-949e-e35436339a0b

### Categories - Create
POST {{baseUrl}}/categories
Content-Type: {{contentType}}
Authorization: Bearer {{ADMIN_TOKEN}}

{
  "name": "Lunch Specials",
  "description": "Delicious lunch options for a quick meal"
}

### Categories - Get All
GET {{baseUrl}}/categories

### Categories - Get By ID
GET {{baseUrl}}/categories/{{categoryId}}

### Categories - Update
PATCH {{baseUrl}}/categories/{{categoryId}}
Content-Type: {{contentType}}
Authorization: Bearer {{ADMIN_TOKEN}}

{
  "name": "Updated Fast Food",
  "description": "Updated description for quick meals"
}

### Categories - Delete
DELETE {{baseUrl}}/categories/{{categoryId}}
Authorization: Bearer {{ADMIN_TOKEN}}

### Menu Items
@menuItemId = 862197c0-d08a-4b0e-8150-d5895847e63d

### Menu Items - Create
POST {{baseUrl}}/menu-items
Content-Type: {{contentType}}
Authorization: Bearer {{ADMIN_TOKEN}}

{
  "name": "Chicken Nuggets",
  "description": "Crispy fried chicken nuggets",
  "price": 5.99,
  "available": true,
  "categoryId": "{{categoryId}}"
}

### Menu Items - Get All
GET {{baseUrl}}/menu-items

### Menu Items - Get By ID
GET {{baseUrl}}/menu-items/{{menuItemId}}

### Menu Items - Get By Category
GET {{baseUrl}}/menu-items/category/{{categoryId}}
Authorization: Bearer {{ADMIN_TOKEN}}

### Menu Items - Update
PATCH {{baseUrl}}/menu-items/{{menuItemId}}
Content-Type: {{contentType}}
Authorization: Bearer {{ADMIN_TOKEN}}

{
  "price": 5.49,
  "available": false
}

### Menu Items - Delete
DELETE {{baseUrl}}/menu-items/{{menuItemId}}
Authorization: Bearer {{ADMIN_TOKEN}}

### Orders
@orderId = a1b2c3d4-e5f6-7890-abcd-ef1234567890
@menuItemId = 459aedee-223d-4da8-b992-ac0b9ac8244d

### Orders - Create
POST {{baseUrl}}/orders
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "orderItems": [
    {
      "menuItemId": "{{menuItemId}}",
      "quantity": 3
    }
  ]
}

### Orders - Get All
GET {{baseUrl}}/orders
Authorization: Bearer {{ADMIN_TOKEN}}

### Orders - Get By User
GET {{baseUrl}}/orders/my-orders
Authorization: Bearer {{token}}

### Orders - Get By ID
@orderId = 62d3f6ef-b507-4d0f-a378-1c13fc34b338
GET {{baseUrl}}/orders/{{orderId}}
Authorization: Bearer {{token}}

### Orders - Update Status
# @orderId = 62d3f6ef-b507-4d0f-a378-1c13fc34b338
PATCH {{baseUrl}}/orders/{{orderId}}/status
Content-Type: {{contentType}}
Authorization: Bearer {{ADMIN_TOKEN}}

{
  "status": "READY"
}

### Orders - Delete
# @orderId = 3861ea32-a468-4a7c-a165-d4b21b31f5bc
DELETE {{baseUrl}}/orders/{{orderId}}
Authorization: Bearer {{ADMIN_TOKEN}}